/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: Generated_RemoteViewModelTest

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_REMOTEVIEWMODELTEST
#define VCZH_WORKFLOW_COMPILER_GENERATED_REMOTEVIEWMODELTEST

#include "../../../../Source/GacUI.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_RemoteViewModelTest_rvmt_MainWindowConstructor___vwsn_rvmt_MainWindow_Initialize_;
}

namespace rvmt
{
	class IViewModel;
	class MainWindowConstructor;
	class MainWindow;

	class IViewModel : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<IViewModel>
	{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IViewModel>;
#endif
	public:
		virtual ::vl::WString Translate(const ::vl::WString& name) = 0;
	};

	class MainWindowConstructor : public ::vl::Object, public ::vl::reflection::Description<MainWindowConstructor>
	{
		friend struct ::vl_workflow_global::__vwsnf1_RemoteViewModelTest_rvmt_MainWindowConstructor___vwsn_rvmt_MainWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindowConstructor>;
#endif
	protected:
		::rvmt::MainWindow* self;
		::vl::Ptr<::rvmt::IViewModel> ViewModel;
		::vl::presentation::compositions::GuiTableComposition* __vwsn_precompile_0;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_1;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_2;
		::vl::presentation::compositions::GuiCellComposition* __vwsn_precompile_3;
		::vl::presentation::compositions::GuiBoundsComposition* __vwsn_precompile_4;
		::vl::presentation::controls::GuiSinglelineTextBox* textName;
		::vl::presentation::controls::GuiLabel* labelGreeting;
		void __vwsn_rvmt_MainWindow_Initialize(::rvmt::MainWindow* __vwsn_this_);
	public:
		MainWindowConstructor();
	};

	class MainWindow : public ::vl::presentation::controls::GuiWindow, public ::rvmt::MainWindowConstructor, public ::vl::reflection::Description<MainWindow>
	{
		friend class ::rvmt::MainWindowConstructor;
		friend struct ::vl_workflow_global::__vwsnf1_RemoteViewModelTest_rvmt_MainWindowConstructor___vwsn_rvmt_MainWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MainWindow>;
#endif
	private:
		::vl::Ptr<::rvmt::IViewModel> __vwsn_parameter_ViewModel;
	public:
		::vl::Ptr<::rvmt::IViewModel> GetViewModel();
		MainWindow(::vl::Ptr<::rvmt::IViewModel> __vwsn_ctor_parameter_ViewModel);
		void __vwsn_instance_ctor_();
		~MainWindow();
	};

}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class RemoteViewModelTest
	{
	public:

		static RemoteViewModelTest& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_RemoteViewModelTest_rvmt_MainWindowConstructor___vwsn_rvmt_MainWindow_Initialize_
	{
		::rvmt::MainWindowConstructor* __vwsnthis_0;

		__vwsnf1_RemoteViewModelTest_rvmt_MainWindowConstructor___vwsn_rvmt_MainWindow_Initialize_(::rvmt::MainWindowConstructor* __vwsnctorthis_0);

		void operator()(::vl::presentation::compositions::GuiGraphicsComposition* sender, ::vl::presentation::compositions::GuiEventArgs* arguments) const;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
