/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: Generated_RemoteProtocolTest

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "DemoReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(rptest::ClickMeTab)
			IMPL_CPP_TYPE_INFO(rptest::ClickMeTabConstructor)
			IMPL_CPP_TYPE_INFO(rptest::DataGridTab)
			IMPL_CPP_TYPE_INFO(rptest::DataGridTabConstructor)
			IMPL_CPP_TYPE_INFO(rptest::DataItem)
			IMPL_CPP_TYPE_INFO(rptest::MainWindow)
			IMPL_CPP_TYPE_INFO(rptest::MainWindowConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::rptest::ClickMeTab)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiTabPage)
				CLASS_MEMBER_BASE(::rptest::ClickMeTabConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::rptest::ClickMeTab*(), NO_PARAMETER)
			END_CLASS_MEMBER(::rptest::ClickMeTab)

			BEGIN_CLASS_MEMBER(::rptest::ClickMeTabConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::rptest::ClickMeTabConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_rptest_ClickMeTab_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(buttonClickMe)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::rptest::ClickMeTabConstructor)

			BEGIN_CLASS_MEMBER(::rptest::DataGridTab)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiTabPage)
				CLASS_MEMBER_BASE(::rptest::DataGridTabConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::rptest::DataGridTab*(), NO_PARAMETER)
				CLASS_MEMBER_FIELD(itemSource)
			END_CLASS_MEMBER(::rptest::DataGridTab)

			BEGIN_CLASS_MEMBER(::rptest::DataGridTabConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::rptest::DataGridTabConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_rptest_DataGridTab_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::rptest::DataGridTabConstructor)

			BEGIN_CLASS_MEMBER(::rptest::DataItem)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::rptest::DataItem>(const ::vl::WString&, const ::vl::WString&, const ::vl::WString&), { L"name" _ L"title" _ L"description" })
				CLASS_MEMBER_METHOD(GetDescription, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetName, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetTitle, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetDescription, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetName, { L"__vwsn_value_" })
				CLASS_MEMBER_METHOD(SetTitle, { L"__vwsn_value_" })
				CLASS_MEMBER_FIELD(__vwsn_prop_Description)
				CLASS_MEMBER_FIELD(__vwsn_prop_Name)
				CLASS_MEMBER_FIELD(__vwsn_prop_Title)
				CLASS_MEMBER_PROPERTY(Description, GetDescription, SetDescription)
				CLASS_MEMBER_PROPERTY(Name, GetName, SetName)
				CLASS_MEMBER_PROPERTY(Title, GetTitle, SetTitle)
			END_CLASS_MEMBER(::rptest::DataItem)

			BEGIN_CLASS_MEMBER(::rptest::MainWindow)
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::rptest::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::rptest::MainWindow*(), NO_PARAMETER)
			END_CLASS_MEMBER(::rptest::MainWindow)

			BEGIN_CLASS_MEMBER(::rptest::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::rptest::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_rptest_MainWindow_Initialize, { L"__vwsn_this_" })
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				CLASS_MEMBER_FIELD(__vwsn_precompile_13)
				CLASS_MEMBER_FIELD(__vwsn_precompile_14)
				CLASS_MEMBER_FIELD(__vwsn_precompile_15)
				CLASS_MEMBER_FIELD(__vwsn_precompile_16)
				CLASS_MEMBER_FIELD(__vwsn_precompile_17)
				CLASS_MEMBER_FIELD(__vwsn_precompile_18)
				CLASS_MEMBER_FIELD(__vwsn_precompile_19)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				CLASS_MEMBER_FIELD(__vwsn_precompile_20)
				CLASS_MEMBER_FIELD(__vwsn_precompile_21)
				CLASS_MEMBER_FIELD(__vwsn_precompile_22)
				CLASS_MEMBER_FIELD(__vwsn_precompile_23)
				CLASS_MEMBER_FIELD(__vwsn_precompile_24)
				CLASS_MEMBER_FIELD(__vwsn_precompile_25)
				CLASS_MEMBER_FIELD(__vwsn_precompile_26)
				CLASS_MEMBER_FIELD(__vwsn_precompile_27)
				CLASS_MEMBER_FIELD(__vwsn_precompile_28)
				CLASS_MEMBER_FIELD(__vwsn_precompile_29)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				CLASS_MEMBER_FIELD(__vwsn_precompile_30)
				CLASS_MEMBER_FIELD(__vwsn_precompile_31)
				CLASS_MEMBER_FIELD(__vwsn_precompile_32)
				CLASS_MEMBER_FIELD(__vwsn_precompile_33)
				CLASS_MEMBER_FIELD(__vwsn_precompile_34)
				CLASS_MEMBER_FIELD(__vwsn_precompile_35)
				CLASS_MEMBER_FIELD(__vwsn_precompile_36)
				CLASS_MEMBER_FIELD(__vwsn_precompile_37)
				CLASS_MEMBER_FIELD(__vwsn_precompile_38)
				CLASS_MEMBER_FIELD(__vwsn_precompile_39)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				CLASS_MEMBER_FIELD(__vwsn_precompile_40)
				CLASS_MEMBER_FIELD(__vwsn_precompile_41)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				CLASS_MEMBER_FIELD(dialogGlobalShortcut)
				CLASS_MEMBER_FIELD(dialogLocalShortcut)
				CLASS_MEMBER_FIELD(dialogQueryClose)
				CLASS_MEMBER_FIELD(menuFileNew)
				CLASS_MEMBER_FIELD(self)
			END_CLASS_MEMBER(::rptest::MainWindowConstructor)

#undef _
			class DemoTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::rptest::ClickMeTab)
					ADD_TYPE_INFO(::rptest::ClickMeTabConstructor)
					ADD_TYPE_INFO(::rptest::DataGridTab)
					ADD_TYPE_INFO(::rptest::DataGridTabConstructor)
					ADD_TYPE_INFO(::rptest::DataItem)
					ADD_TYPE_INFO(::rptest::MainWindow)
					ADD_TYPE_INFO(::rptest::MainWindowConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadDemoTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new DemoTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
