/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "VlppOS.h"
#include "Vlpp.h"

/***********************************************************************
.\NETWORKPROTOCOL.WINDOWS.H
***********************************************************************/
/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)

Interfaces:
***********************************************************************/

#ifndef VCZH_INTERPROCESS_WINDOWS_NETWORKPROTOCOL
#define VCZH_INTERPROCESS_WINDOWS_NETWORKPROTOCOL

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <http.h>
#define RPC_USE_NATIVE_WCHAR
#include <rpc.h>
#include <winhttp.h>


namespace vl::inter_process
{
	/*
	* GET: /Request
	* To connect and initialize the server.
	* Returns available URLs.
	*
	* It can only be called once, all subsequence calls will be rejected.
	*/
	constexpr const wchar_t* HttpServerUrl_Connect = L"/VlppInterProcess/Connect";

	/*
	* POST: /Request/GUID
	* Client should always maintain a living request on the server.
	*
	* Returns only when a request is issued.
	* It will be pending or timeout if no request is issued.
	* If a request is issued but no living request available, it waits.
	*/
	constexpr const wchar_t* HttpServerUrl_Request = L"/VlppInterProcess/Request";

	/*
	* POST: /Response/GUID
	* To send responses or events to the server.
	* Returns nothing.
	*/
	constexpr const wchar_t* HttpServerUrl_Response = L"/VlppInterProcess/Response";
}

#endif

/***********************************************************************
.\HTTPCLIENT.WINDOWS.H
***********************************************************************/
/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)

Interfaces:
	HttpClient

***********************************************************************/

#ifndef VCZH_INTERPROCESS_WINDOWS_HTTPCLIENT
#define VCZH_INTERPROCESS_WINDOWS_HTTPCLIENT


namespace vl::inter_process
{

class HttpClient : public Object, public virtual INetworkProtocolConnection, public virtual INetworkProtocolClient
{
protected:

	enum class State
	{
		Ready,
		WaitForServerConnection,
		Running,
		Stopping,
	};

	State											state = State::Ready;
	INetworkProtocolCallback*						callback = nullptr;
	WString											baseUrl;

	HINTERNET										httpSession = NULL;
	HINTERNET										httpConnection = NULL;
	WString											urlConnect;
	WString											urlRequest;
	WString											urlResponse;

	atomic_vint										pendingCallbacks = 0;
	atomic_vint										createdRequestIds = 0;
	EventObject										eventPendingCallbacks;
	void											BeginPendingCallback();
	void											EndPendingCallback();
	void											QueueCallback(const Func<void()>& proc);
	vint											FindActiveRequestUnsafe(HINTERNET httpRequest, vint requestId);
	void											AttachRequest(HINTERNET httpRequest, vint requestId = 0);
	void											CloseRequest(HINTERNET httpRequest, vint requestId = 0);
	void											OnRequestHandleClosing(HINTERNET httpRequest, vint requestId = 0);

/***********************************************************************
HttpClient (Reading)
***********************************************************************/

protected:
	static constexpr vint32_t						HttpRespondBodyStep = 65536;
	collections::Array<char8_t>						httpRespondBodyBuffer;
	DWORD											httpRespondBodyBufferWriting = 0;
	DWORD											httpRespondBodyBufferWritingAvailable = 0;

	void											RaiseErrorUnsafe(WString errorMessage);
public:

	void											BeginReadingLoopUnsafe() override;

/***********************************************************************
HttpClient (WaitForServer)
***********************************************************************/

protected:

	HANDLE											hEventWaitForServer = INVALID_HANDLE_VALUE;
	DWORD											dwInternetStatus_WaitForServer = 0;
	DWORD											dwStatusInformationLength_WaitForServer = 0;

public:
	
	INetworkProtocolConnection*						GetConnection() override;
	void											WaitForServer() override;
	ClientStatus									GetStatus() override;

/***********************************************************************
HttpClient (Writing)
***********************************************************************/

protected:
	class HttpResponseReading : public Object
	{
	public:
		collections::Array<char8_t>					bodyBuffer;
		DWORD										bodyBufferWriting = 0;
		DWORD										bodyBufferWritingAvailable = 0;
	};

	class HttpRequestContext : public Object
	{
	public:
		HttpClient*									client = nullptr;
		HINTERNET									httpRequest = NULL;
		vint										requestId = 0;
		U8String									requestBody;
		Ptr<HttpResponseReading>					responseReading;
	};

	class HttpActiveRequest
	{
	public:
		HINTERNET									httpRequest = NULL;
		vint										requestId = -1;
	};

	SpinLock										httpActiveRequestsLock;
	collections::List<HttpActiveRequest>			httpActiveRequests;


public:

	void											SendString(const WString& str) override;

/***********************************************************************
HttpClient
***********************************************************************/

public:
	HttpClient(const WString _baseUrl, vint port);
	~HttpClient();

	void											InstallCallback(INetworkProtocolCallback* _callback) override;
	void											Stop() override;
};

}

#endif


/***********************************************************************
.\HTTPSERVER.WINDOWS.H
***********************************************************************/
/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)

Interfaces:
	HttpServer

***********************************************************************/

#ifndef VCZH_INTERPROCESS_WINDOWS_HTTPSERVER
#define VCZH_INTERPROCESS_WINDOWS_HTTPSERVER


namespace vl::inter_process
{

class HttpServer;

class HttpServerConnection : public Object, public virtual INetworkProtocolConnection
{
	friend class HttpServer;
protected:
	HttpServer*										server = nullptr;
	WString											guid;
	INetworkProtocolCallback*						callback = nullptr;

	SpinLock										lockQueuedStrings;
	collections::List<WString>						queuedStrings;

	SpinLock										pendingRequestLock;
	HTTP_REQUEST_ID									httpPendingRequestId = HTTP_NULL_ID;
	collections::List<WString>						pendingRequestsToSend;
	bool											submittingResponse = false;
	collections::List<WString>						responsesToSubmit;

	// All following functions must be called inside SPIN_LOCK(pendingRequestLock)
	void											OnCancelCurrentHttpRequestForPendingRequest();
	void											OnNewHttpRequestForPendingRequest(HTTP_REQUEST_ID httpRequestId);

	WString											SubmitResponse(PHTTP_REQUEST pRequest);

public:
	void											InstallCallback(INetworkProtocolCallback* _callback) override;
	void											BeginReadingLoopUnsafe() override;
	void											SendString(const WString& str) override;
	void											Stop() override;

	static WString									GenerateNewGuid();
};

class HttpServer : public Object, public virtual INetworkProtocolServer
{
	static constexpr vint32_t						HttpBodyInitSize = 1024;

	friend class HttpServerConnection;
	using ConnectionMap = collections::Dictionary<WString, Ptr<HttpServerConnection>>;
protected:
	WString											baseUrl;
	WString											urlConnect;
	WString											urlRequestPrefix;
	WString											urlResponsePrefix;

	// covers connections
	SpinLock										lockConnections;
	ConnectionMap									connections;

	HANDLE											httpRequestQueue = INVALID_HANDLE_VALUE;
	HTTP_SERVER_SESSION_ID							httpSessionId = HTTP_NULL_ID;
	HTTP_URL_GROUP_ID								httpUrlGroupId = HTTP_NULL_ID;

/***********************************************************************
HttpServer (ListenToHttpRequest)
***********************************************************************/

protected:

	enum class State
	{
		Ready,
		Running,
		Stopping,
	};

	State											state = State::Ready;

	collections::Array<BYTE>						bufferRequest;
	HANDLE											hWaitHandleRequest = INVALID_HANDLE_VALUE;
	OVERLAPPED										overlappedRequest;
	HANDLE											hEventRequest = INVALID_HANDLE_VALUE;

	void											OnHttpConnectionBrokenUnsafe();
	void											OnHttpRequestReceivedUnsafe(PHTTP_REQUEST pRequest);
	ULONG											ListenToHttpRequest_Init(OVERLAPPED* overlapped);
	ULONG											ListenToHttpRequest_InitMoreData(ULONG* bytesReturned);
	ULONG											ListenToHttpRequest_OverlappedMoreData(vint expectedBufferSize);
	void											ListenToHttpRequest();

/***********************************************************************
HttpServer (BeginReadingLoopUnsafe)
***********************************************************************/

protected:


/***********************************************************************
HttpServer (Writing)
***********************************************************************/

protected:

	static void										Send404Response(HANDLE httpRequestQueue, HTTP_REQUEST_ID requestId, PCSTR reason);
	static void										SendOptionsResponse(HANDLE httpRequestQueue, HTTP_REQUEST_ID requestId);
	static ULONG									SendResponse(HANDLE httpRequestQueue, HTTP_REQUEST_ID requestId, const WString& str);

/***********************************************************************
HttpServer
***********************************************************************/

public:
	HttpServer(const WString _baseUrl, vint port);
	~HttpServer();
	
	WaitForClientResult								OnClientConnected(INetworkProtocolConnection* connection) override;
	void											Start() override;
	void											Stop() override;
	bool											IsStopped() override;
};

}

#endif


/***********************************************************************
.\NAMEDPIPE.WINDOWS.H
***********************************************************************/
/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)

Interfaces:
	NamedPipeServer
	NamedPipeClient

***********************************************************************/

#ifndef VCZH_INTERPROCESS_WINDOWS_NAMEDPIPE
#define VCZH_INTERPROCESS_WINDOWS_NAMEDPIPE


namespace vl::inter_process
{

class NamedPipeServer;

class NamedPipeConnection : public Object, public virtual INetworkProtocolConnection
{
	friend class NamedPipeServer;
// -----------------------------------------------------------------------
// Reading
// -----------------------------------------------------------------------

private:
	bool											firstRead = true;
	atomic_vint										stopped = 0;
	collections::Array<BYTE>						bufferReadFile;
	stream::MemoryStream							streamReadFile;
	HANDLE											hWaitHandleReadFile = INVALID_HANDLE_VALUE;
	OVERLAPPED										overlappedReadFile;
	HANDLE											hEventReadFile = INVALID_HANDLE_VALUE;

	void											BeginReadingUnsafe();
	void											SubmitReadBufferUnsafe(vint bytes);
	void											EndReadingUnsafe();

public:
	void											BeginReadingLoopUnsafe() override;

// -----------------------------------------------------------------------
// Writing
// -----------------------------------------------------------------------
private:
	SpinLock										lockWrite;
	stream::MemoryStream							streamWriteFile;
	OVERLAPPED										overlappedWriteFile;
	HANDLE											hEventWriteFile = INVALID_HANDLE_VALUE;

	vint32_t										WriteInt32ToStream(vint32_t number);
	vint32_t										WriteStringToStream(const WString& str);
	void											BeginSendStream();
	void											EndSendStream(vint32_t bytes);

protected:
	void											SendString(const WString& str) override;

// -----------------------------------------------------------------------
// Connection
// -----------------------------------------------------------------------

protected:
	// NamedPipe doesn't support a single message that is larger than 64K
	static constexpr vint32_t						MaxMessageSize = 65536;

	NamedPipeServer*								server = nullptr;
	INetworkProtocolCallback*						callback = nullptr;
	HANDLE											hPipe = INVALID_HANDLE_VALUE;

	void											OnDisconnected();

	NamedPipeConnection(HANDLE _hPipe);

public:
	~NamedPipeConnection();

	void											InstallCallback(INetworkProtocolCallback* _callback) override;
	void											Stop() override;
};

class NamedPipeServer : public Object, public virtual INetworkProtocolServer
{
	friend class NamedPipeConnection;
protected:
	class PendingConnection : public Object
	{
	public:
		NamedPipeServer*								server = nullptr;
		Ptr<NamedPipeConnection>						connection;
		HANDLE											hWaitHandleConnect = INVALID_HANDLE_VALUE;
		OVERLAPPED										overlappedConnect;
		HANDLE											hEventConnect = INVALID_HANDLE_VALUE;

		PendingConnection(NamedPipeServer* _server, Ptr<NamedPipeConnection> _connection);
		~PendingConnection();

		void											Stop();
	};

	static HANDLE									ServerCreatePipe(const WString& pipeName);

	WString											pipeName;

	// covers started, stopped, connections and pendingConnections
	SpinLock										lockConnections;
	bool											started = false;
	bool											stopped = false;
	collections::List<Ptr< NamedPipeConnection>>	connections;
	collections::List<Ptr<PendingConnection>>		pendingConnections;

	void											BeginListening();
	void											CompletePendingConnection(Ptr<PendingConnection> pendingConnection, bool connected);
	void											CompletePendingConnection(PendingConnection* pendingConnection, bool connected);

public:
	NamedPipeServer(const WString& _pipeName);
	~NamedPipeServer();

	WaitForClientResult								OnClientConnected(INetworkProtocolConnection* connection) override;
	void											Start() override;
	void											Stop() override;
	bool											IsStopped() override;
};

class NamedPipeClient : public NamedPipeConnection, public virtual INetworkProtocolClient
{
protected:
	static HANDLE									ClientCreatePipe(const WString& pipeName);
	ClientStatus									status = ClientStatus::Ready;

public:
	NamedPipeClient(const WString& _pipeName);
	~NamedPipeClient();

	INetworkProtocolConnection*						GetConnection() override;
	void											WaitForServer() override;
	ClientStatus									GetStatus() override;
	void											Stop() override;
};

}

#endif

