/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "GitViewReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(gitview::DiffLineTemplate)
			IMPL_CPP_TYPE_INFO(gitview::DiffLineTemplateConstructor)
			IMPL_CPP_TYPE_INFO(gitview::IDiffLine)
			IMPL_CPP_TYPE_INFO(gitview::IEntry)
			IMPL_CPP_TYPE_INFO(gitview::IGitViewModel)
			IMPL_CPP_TYPE_INFO(gitview::MainWindow)
			IMPL_CPP_TYPE_INFO(gitview::MainWindowConstructor)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_CLASS_MEMBER(::gitview::DiffLineTemplate)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_cpp_Friend, ::vl::reflection::description::GetTypeDescriptor(::vl::WString::Unmanaged(L"gitview::DiffLineTemplateConstructor")))
				CLASS_MEMBER_BASE(::vl::presentation::templates::GuiTextListItemTemplate)
				CLASS_MEMBER_BASE(::gitview::DiffLineTemplateConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gitview::DiffLineTemplate*(::vl::Ptr<::gitview::IDiffLine>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Private)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gitview::DiffLineTemplate)

			BEGIN_CLASS_MEMBER(::gitview::DiffLineTemplateConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gitview::DiffLineTemplateConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gitview_DiffLineTemplate_Initialize, { L"__vwsn_this_" })
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(ViewModel)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(self)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
			END_CLASS_MEMBER(::gitview::DiffLineTemplateConstructor)

			BEGIN_INTERFACE_MEMBER(::gitview::IDiffLine)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetBackground, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetIsSeparator, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetText, NO_PARAMETER)
				CLASS_MEMBER_EVENT(BackgroundChanged)
				CLASS_MEMBER_EVENT(IsSeparatorChanged)
				CLASS_MEMBER_EVENT(TextChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Background, GetBackground, BackgroundChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(IsSeparator, GetIsSeparator, IsSeparatorChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Text, GetText, TextChanged)
			END_INTERFACE_MEMBER(::gitview::IDiffLine)

			BEGIN_INTERFACE_MEMBER(::gitview::IEntry)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetChildren, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetText, NO_PARAMETER)
				CLASS_MEMBER_EVENT(ChildrenChanged)
				CLASS_MEMBER_EVENT(TextChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Children, GetChildren, ChildrenChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Text, GetText, TextChanged)
			END_INTERFACE_MEMBER(::gitview::IEntry)

			BEGIN_INTERFACE_MEMBER(::gitview::IGitViewModel)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetBranchIndex, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetBranches, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetCanPull, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetChangeDiff, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetChanges, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetCommits, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetFiles, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetHistoryDiff, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetRepositoryName, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetRevision, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetStatus, NO_PARAMETER)
				CLASS_MEMBER_METHOD(Pull, { L"rebaseOnConflict" })
				CLASS_MEMBER_METHOD(Refresh, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SelectChange, { L"entry" })
				CLASS_MEMBER_METHOD(SelectCommit, { L"entry" })
				CLASS_MEMBER_METHOD(SelectFile, { L"entry" })
				CLASS_MEMBER_METHOD(SetBranchIndex, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(BranchIndexChanged)
				CLASS_MEMBER_EVENT(BranchesChanged)
				CLASS_MEMBER_EVENT(CanPullChanged)
				CLASS_MEMBER_EVENT(ChangeDiffChanged)
				CLASS_MEMBER_EVENT(ChangesChanged)
				CLASS_MEMBER_EVENT(CommitsChanged)
				CLASS_MEMBER_EVENT(FilesChanged)
				CLASS_MEMBER_EVENT(HistoryDiffChanged)
				CLASS_MEMBER_EVENT(RepositoryNameChanged)
				CLASS_MEMBER_EVENT(RevisionChanged)
				CLASS_MEMBER_EVENT(StatusChanged)
				CLASS_MEMBER_PROPERTY_EVENT(BranchIndex, GetBranchIndex, SetBranchIndex, BranchIndexChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Branches, GetBranches, BranchesChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(CanPull, GetCanPull, CanPullChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(ChangeDiff, GetChangeDiff, ChangeDiffChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Changes, GetChanges, ChangesChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Commits, GetCommits, CommitsChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Files, GetFiles, FilesChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(HistoryDiff, GetHistoryDiff, HistoryDiffChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(RepositoryName, GetRepositoryName, RepositoryNameChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Revision, GetRevision, RevisionChanged)
				CLASS_MEMBER_PROPERTY_EVENT_READONLY(Status, GetStatus, StatusChanged)
			END_INTERFACE_MEMBER(::gitview::IGitViewModel)

			BEGIN_CLASS_MEMBER(::gitview::MainWindow)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_cpp_Friend, ::vl::reflection::description::GetTypeDescriptor(::vl::WString::Unmanaged(L"gitview::MainWindowConstructor")))
				CLASS_MEMBER_BASE(::vl::presentation::controls::GuiWindow)
				CLASS_MEMBER_BASE(::gitview::MainWindowConstructor)
				CLASS_MEMBER_CONSTRUCTOR(::gitview::MainWindow*(::vl::Ptr<::gitview::IGitViewModel>), { L"__vwsn_ctor_parameter_ViewModel" })
				CLASS_MEMBER_METHOD(GetRevision, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetViewModel, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetRevision, { L"__vwsn_value_" })
				CLASS_MEMBER_EVENT(RevisionChanged)
				CLASS_MEMBER_FIELD(__vwsn_parameter_ViewModel)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Private)
				CLASS_MEMBER_FIELD(__vwsn_prop_Revision)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Private)
				CLASS_MEMBER_PROPERTY_EVENT(Revision, GetRevision, SetRevision, RevisionChanged)
				CLASS_MEMBER_PROPERTY_READONLY(ViewModel, GetViewModel)
			END_CLASS_MEMBER(::gitview::MainWindow)

			BEGIN_CLASS_MEMBER(::gitview::MainWindowConstructor)
				CLASS_MEMBER_BASE(::vl::reflection::DescriptableObject)
				CLASS_MEMBER_CONSTRUCTOR(::vl::Ptr<::gitview::MainWindowConstructor>(), NO_PARAMETER)
				CLASS_MEMBER_METHOD(__vwsn_gitview_MainWindow_Initialize, { L"__vwsn_this_" })
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_0)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_1)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_10)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_11)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_12)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_13)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_14)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_15)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_16)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_17)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_18)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_19)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_2)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_20)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_21)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_22)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_23)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_24)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_25)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_26)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_27)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_28)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_29)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_3)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_30)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_31)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_32)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_33)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_34)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_35)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_36)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_37)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_38)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_39)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_4)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_40)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_41)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_42)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_5)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_6)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_7)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_8)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(__vwsn_precompile_9)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(ViewModel)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(branches)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(changes)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(commits)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(files)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(self)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
				CLASS_MEMBER_FIELD(status)
				ATTRIBUTE_MEMBER(::vl::__vwsn::att_cpp_Protected)
			END_CLASS_MEMBER(::gitview::MainWindowConstructor)

#undef _
			class GitViewTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::gitview::DiffLineTemplate)
					ADD_TYPE_INFO(::gitview::DiffLineTemplateConstructor)
					ADD_TYPE_INFO(::gitview::IDiffLine)
					ADD_TYPE_INFO(::gitview::IEntry)
					ADD_TYPE_INFO(::gitview::IGitViewModel)
					ADD_TYPE_INFO(::gitview::MainWindow)
					ADD_TYPE_INFO(::gitview::MainWindowConstructor)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadGitViewTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new GitViewTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
