/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "GacUI.h"
#include "Vlpp.h"
#include "VlppGlrParser.h"
#include "VlppOS.h"
#include "VlppReflection.h"
#include "VlppRegex.h"
#include "VlppWorkflowLibrary.h"

#include "..\..\Source\RemotingHelpers\AutomationService\AutomationServiceHost.h"
#include "..\..\Source\RemotingHelpers\AutomationService\MiniHttpAutomationService.h"
#include "..\..\Source\RemotingHelpers\RemotingClient\RemotingChannelClient.h"
#include "..\..\Source\RemotingHelpers\RemotingClient\RemotingClient.h"
#include "..\..\Source\RemotingHelpers\RemotingServer\RemotingChannelServer.h"
