/***********************************************************************
THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY
DEVELOPER: Zihan Chen(vczh)
***********************************************************************/
#include "Test.RemotingHelpers.h"

/***********************************************************************
.\RENDERERCLIENT\REMOTEPROTOCOLRENDERERCLIENT.CPP
***********************************************************************/

namespace vl::presentation::remoting
{
	using namespace remoteprotocol::channeling;
	using namespace remote_renderer;

	RemoteProtocolRendererClient::RemoteProtocolRendererClient(
		Ptr<inter_process::INetworkProtocolClient> client,
		Ptr<glr::json::Parser> parser,
		const WString& _fatalTitle
		)
		: Base(client, parser)
		, fatalTitle(_fatalTitle)
	{
		CHECK_ERROR(fatalTitle != L"", L"RemoteProtocolRendererClient::RemoteProtocolRendererClient(...)#The fatal title is empty.");
	}

	void RemoteProtocolRendererClient::QueueMainThreadTask(const Func<void()>& task)
	{
		GuiRemoteProtocolAsyncJsonChannelRenderer* targetChannel = nullptr;
		SPIN_LOCK(lockState)
		{
			if (!stopping)
			{
				targetChannel = asyncRendererChannel;
			}
		}
		if (targetChannel)
		{
			targetChannel->QueueMainThreadTask(task);
		}
	}

	void RemoteProtocolRendererClient::ProcessFatalError(const WString& errorMessage)
	{
		GuiRemoteRendererSingle* targetRenderer = nullptr;
		AutomationServiceRenderer* targetAutomationService = nullptr;
		SPIN_LOCK(lockState)
		{
			if (
				!stopping &&
				triggeredFatalError &&
				!retainedFatalError &&
				renderer &&
				rendererAutomationService &&
				!renderer->IsDisconnectedFromCore()
				)
			{
				targetRenderer = renderer;
				targetAutomationService = rendererAutomationService;
			}
		}
		if (!targetRenderer)
		{
			return;
		}

		bool retainRenderer = true;
#if !defined VCZH_GCC || defined VCZH_APPLE
		auto mainWindow = GetCurrentController()->WindowService()->GetMainWindow();
		auto result = GetCurrentController()->DialogService()->ShowMessageBox(
			mainWindow,
			errorMessage + WString::Unmanaged(L"\r\n\r\nDo you want to close the renderer?"),
			fatalTitle,
			INativeDialogService::DisplayYesNo,
			INativeDialogService::DefaultFirst,
			INativeDialogService::IconError
			);
		retainRenderer = result != INativeDialogService::SelectYes;
#endif
		if (retainRenderer)
		{
			SPIN_LOCK(lockState)
			{
				if (
					!stopping &&
					renderer == targetRenderer &&
					rendererAutomationService == targetAutomationService
					)
				{
					retainedFatalError = true;
				}
			}
			targetRenderer->RetainByFatalError(errorMessage);
			targetAutomationService->SetFatalError(Nullable<WString>(errorMessage));
		}
		else
		{
			targetRenderer->ForceExitByFatelError();
		}
	}

	void RemoteProtocolRendererClient::ProcessDisconnected()
	{
		GuiRemoteProtocolAsyncJsonChannelRenderer* targetChannel = nullptr;
		GuiRemoteRendererSingle* targetRenderer = nullptr;
		bool forceRendererToExit = false;
		SPIN_LOCK(lockState)
		{
			if (stopping || triggeredFatalError || (renderer && renderer->IsDisconnectedFromCore()))
			{
				return;
			}
			targetChannel = asyncRendererChannel;
			targetRenderer = renderer;
			forceRendererToExit = targetRenderer && !targetRenderer->IsDisconnectedFromCore();
		}
		if (targetChannel)
		{
			targetChannel->Detach();
		}
		if (forceRendererToExit)
		{
			targetRenderer->ForceExitByFatelError();
		}
	}

	void RemoteProtocolRendererClient::SetRenderer(GuiRemoteRendererSingle* value)
	{
		SPIN_LOCK(lockState)
		{
			renderer = value;
		}
	}

	void RemoteProtocolRendererClient::SetAsyncRendererChannel(GuiRemoteProtocolAsyncJsonChannelRenderer* value)
	{
		SPIN_LOCK(lockState)
		{
			asyncRendererChannel = value;
		}
	}

	void RemoteProtocolRendererClient::SetRendererAutomationService(AutomationServiceRenderer* value)
	{
		SPIN_LOCK(lockState)
		{
			rendererAutomationService = value;
		}
	}

	void RemoteProtocolRendererClient::BeginStopping()
	{
		GuiRemoteProtocolAsyncJsonChannelRenderer* targetChannel = nullptr;
		SPIN_LOCK(lockState)
		{
			if (!stopping)
			{
				stopping = true;
				targetChannel = asyncRendererChannel;
			}
		}
		if (targetChannel)
		{
			targetChannel->Detach();
		}
	}

	bool RemoteProtocolRendererClient::IsFatalErrorRetained()
	{
		bool retained = false;
		SPIN_LOCK(lockState)
		{
			retained = retainedFatalError;
		}
		return retained;
	}

	void RemoteProtocolRendererClient::OnReadError(const WString& errorMessage)
	{
		GuiRemoteProtocolAsyncJsonChannelRenderer* targetChannel = nullptr;
		SPIN_LOCK(lockState)
		{
			if (!stopping && !triggeredFatalError && asyncRendererChannel)
			{
				triggeredFatalError = true;
				targetChannel = asyncRendererChannel;
			}
		}
		if (targetChannel)
		{
			targetChannel->QueueMainThreadTask(Func<void()>([this, errorMessage]()
			{
				ProcessFatalError(errorMessage);
			}));
		}
	}

	void RemoteProtocolRendererClient::OnLocalError(const WString&, bool fatal)
	{
		if (fatal)
		{
			QueueMainThreadTask(Func<void()>([this]()
			{
				ProcessDisconnected();
			}));
		}
	}

	void RemoteProtocolRendererClient::OnDisconnected()
	{
		Base::OnDisconnected();
		QueueMainThreadTask(Func<void()>([this]()
		{
			ProcessDisconnected();
		}));
	}
}


/***********************************************************************
.\RVMT\VIEWMODELHOSTCLIENT.CPP
***********************************************************************/
#include <cstdlib>

namespace vl::presentation::remoting
{
	using namespace collections;
	using namespace rpc_controller::channeling;

	[[noreturn]] void ExitViewModelHostProcess(vint exitCode)
	{
		std::_Exit((int)exitCode);
	}

	ViewModelHostClient::ViewModelHostClient(
		Ptr<inter_process::INetworkProtocolClient> networkClient,
		Ptr<glr::json::Parser> parser,
		Ptr<TaskQueue> taskQueue
		)
		: JsonNetworkChannelClient(networkClient, parser)
	{
		channelNames.Add(ViewModelChannelName, nullptr);
		channelNames.Add(ViewModelReadyChannelName, nullptr);
		dispatcher = Ptr(new RpcDispatcherClient(taskQueue));
	}

	const JsonChannelClient::ChannelNameList& ViewModelHostClient::OnGetChannelNames()
	{
		return channelNames.Keys();
	}

	void ViewModelHostClient::OnConnected(vint)
	{
	}

	void ViewModelHostClient::OnDisconnected()
	{
		ExitViewModelHostProcess(1);
	}

	void ViewModelHostClient::OnReadError(const WString&)
	{
		ExitViewModelHostProcess(1);
	}

	void ViewModelHostClient::OnLocalError(const WString&, bool fatal)
	{
		if (fatal)
		{
			ExitViewModelHostProcess(1);
		}
	}

	void ViewModelHostClient::Connect()
	{
		List<WString> waitingForServices;
		dispatcher->WaitForServer(
			this,
			GetChannels()[ViewModelChannelName],
			waitingForServices
			);
		controlChannel = GetChannels()[ViewModelReadyChannelName];
		CHECK_ERROR(controlChannel, L"ViewModelHostClient::Connect()#The control channel is null.");
	}

	void ViewModelHostClient::SendReady()
	{
		CHECK_ERROR(controlChannel, L"ViewModelHostClient::SendReady()#The control channel is null.");
		controlChannel->BroadcastFromClient(CreateViewModelReadyMessage());
		bool disconnected = false;
		controlChannel->BatchWrite(disconnected);
		if (disconnected)
		{
			ExitViewModelHostProcess(1);
		}
	}

	RpcDispatcherClient* ViewModelHostClient::GetDispatcher()
	{
		return dispatcher.Obj();
	}
}


/***********************************************************************
.\RVMT\VIEWMODELHOSTSERVER.CPP
***********************************************************************/

namespace vl::presentation::remoting
{
	using namespace collections;
	using namespace rpc_controller::channeling;

/***********************************************************************
TaskQueueThread
***********************************************************************/

	class TaskQueueThread : public Thread
	{
	private:
		Ptr<TaskQueue>										taskQueue;

	protected:
		void Run() override
		{
			try
			{
				taskQueue->RunTaskQueue();
			}
			catch (...)
			{
				std::_Exit(1);
			}
		}

	public:
		TaskQueueThread(Ptr<TaskQueue> _taskQueue)
			: taskQueue(_taskQueue)
		{
			CHECK_ERROR(taskQueue, L"TaskQueueThread::TaskQueueThread(...)#The task queue is null.");
		}
	};

/***********************************************************************
RpcBroadcastingLocalClient
***********************************************************************/

	class RpcBroadcastingLocalClient
		: public JsonLocalChannelClient
		, protected inter_process::IChannelReader<JsonPackage>
	{
	private:
		JsonChannelClient::ChannelMap						channelNames;
		Ptr<RpcJsonDispatcherServerForTaskQueue>			dispatcher;
		Func<void(vint, const JsonPackage&)>				controlCallback;
		JsonChannel*										controlChannel = nullptr;

	protected:
		void OnRead(vint senderClientId, const JsonPackage& package) override
		{
			controlCallback(senderClientId, package);
		}

	public:
		RpcBroadcastingLocalClient(
			Ptr<glr::json::Parser> parser,
			const Func<void(vint, const JsonPackage&)>& _controlCallback
			)
			: JsonLocalChannelClient(parser)
			, controlCallback(_controlCallback)
		{
			CHECK_ERROR(controlCallback, L"RpcBroadcastingLocalClient::RpcBroadcastingLocalClient(...)#The control callback is null.");
			channelNames.Add(ViewModelChannelName, nullptr);
			channelNames.Add(ViewModelReadyChannelName, nullptr);
		}

		const JsonChannelClient::ChannelNameList& OnGetChannelNames() override
		{
			return channelNames.Keys();
		}

		vint Connect(JsonChannelServer* channelServer, Ptr<JsonChannelClient> self, Ptr<TaskQueue> taskQueue)
		{
			CHECK_ERROR(channelServer, L"RpcBroadcastingLocalClient::Connect(...)#The channel server is null.");
			CHECK_ERROR(self, L"RpcBroadcastingLocalClient::Connect(...)#The shared local client is null.");
			auto clientId = channelServer->ConnectLocalClient(self);
			CHECK_ERROR(clientId != -1, L"RpcBroadcastingLocalClient::Connect(...)#Failed to connect the broadcasting client.");
			controlChannel = GetChannels()[ViewModelReadyChannelName];
			CHECK_ERROR(controlChannel, L"RpcBroadcastingLocalClient::Connect(...)#The control channel is null.");
			controlChannel->Initialize(this);
			dispatcher = Ptr(new RpcJsonDispatcherServerForTaskQueue(
				this,
				GetChannels()[ViewModelChannelName],
				taskQueue
				));
			return clientId;
		}

		RpcJsonDispatcherServer* GetDispatcher()
		{
			CHECK_ERROR(dispatcher, L"RpcBroadcastingLocalClient::GetDispatcher()#The client is not connected.");
			return dispatcher.Obj();
		}
	};

/***********************************************************************
RpcServiceAccessLocalClient
***********************************************************************/

	class RpcServiceAccessLocalClient : public JsonLocalChannelClient
	{
	private:
		JsonChannelClient::ChannelMap						channelNames;
		Ptr<RpcDispatcherClient>							dispatcher;

	public:
		RpcServiceAccessLocalClient(Ptr<glr::json::Parser> parser)
			: JsonLocalChannelClient(parser)
		{
			channelNames.Add(ViewModelChannelName, nullptr);
		}

		const JsonChannelClient::ChannelNameList& OnGetChannelNames() override
		{
			return channelNames.Keys();
		}

		vint Connect(
			JsonChannelServer* channelServer,
			Ptr<JsonChannelClient> self,
			Ptr<TaskQueue> taskQueue,
			vint serverClientId,
			const List<WString>& requiredServiceNames
			)
		{
			dispatcher = Ptr(new RpcDispatcherClient(taskQueue));
			auto clientId = dispatcher->ConnectLocalServer(
				channelServer,
				self,
				GetChannels()[ViewModelChannelName],
				requiredServiceNames
				);
			CHECK_ERROR(clientId != -1, L"RpcServiceAccessLocalClient::Connect(...)#Failed to connect the requester client.");
			dispatcher->SetServerLocalClientId(serverClientId);
			return clientId;
		}

		RpcDispatcherClient* GetDispatcher()
		{
			CHECK_ERROR(dispatcher, L"RpcServiceAccessLocalClient::GetDispatcher()#The client is not connected.");
			return dispatcher.Obj();
		}
	};

/***********************************************************************
RpcServerHelpers
***********************************************************************/

	void RpcServerHelpers::FinalizeRpcOnTaskQueue()
	{
		EventObject finalized;
		CHECK_ERROR(finalized.CreateAutoUnsignal(false), L"RpcServerHelpers::FinalizeRpcOnTaskQueue()#Failed to create the finalization event.");
		taskQueue->QueueTask(Func<void()>([&]()
		{
			requesterDispatcher->FinalizeRpc();
			finalized.Signal();
		}));
		finalized.Wait();
	}

	RpcServerHelpers::RpcServerHelpers(Ptr<glr::json::Parser> parser)
		: phase(RequesterPhase::Starting)
		, taskQueue(Ptr(new TaskQueue))
	{
		CHECK_ERROR(parser, L"RpcServerHelpers::RpcServerHelpers(...)#The JSON parser is null.");

		taskQueueThread = Ptr(new TaskQueueThread(taskQueue));
		broadcastingClient = Ptr(new RpcBroadcastingLocalClient(
			parser,
			Func<void(vint, const JsonPackage&)>([this](vint senderClientId, const JsonPackage& package)
			{
				OnControlMessage(senderClientId, package);
			})
			));
		requesterClient = Ptr(new RpcServiceAccessLocalClient(parser));
	}

	RpcServerHelpers::~RpcServerHelpers() = default;

	bool RpcServerHelpers::TryAcceptHost(vint clientId)
	{
		bool accepted = false;
		SPIN_LOCK(lockState)
		{
			if (
				admissionReady &&
				phase == RequesterPhase::Starting &&
				!hostEverAccepted &&
				clientId != InvalidRemoteViewModelClientId
				)
			{
				hostId = clientId;
				hostEverAccepted = true;
				accepted = true;
			}
		}
		return accepted;
	}

	void RpcServerHelpers::RegisterHost(vint clientId)
	{
		SPIN_LOCK(lockState)
		{
			CHECK_ERROR(
				hostId == clientId && !brokerRegistrationClaimed,
				L"RpcServerHelpers received Ready from an unexpected client."
				);
			brokerRegistrationClaimed = true;
		}

		CS_LOCK(lockBroker)
		{
			bool shouldRegister = false;
			SPIN_LOCK(lockState)
			{
				shouldRegister = hostId == clientId && brokerRegistrationClaimed;
			}
			if (shouldRegister)
			{
				brokerDispatcher->RegisterClient(clientId);
			}
		}
	}

	void RpcServerHelpers::OnControlMessage(vint senderClientId, const JsonPackage& package)
	{
		if (IsViewModelReadyMessage(package))
		{
			RegisterHost(senderClientId);
			return;
		}
		CHECK_ERROR(false, L"RpcServerHelpers received an unexpected control message.");
	}

	void RpcServerHelpers::OnClientDisconnected(vint clientId)
	{
		bool hostDisconnected = false;
		bool disconnectBroker = false;
		RpcDispatcherClient* dispatcherToInject = nullptr;
		SPIN_LOCK(lockState)
		{
			if (hostId == clientId)
			{
				hostId = InvalidRemoteViewModelClientId;
				hostDisconnected = phase != RequesterPhase::Stopping;
				hostLossClaimed = hostDisconnected;
				disconnectBroker = brokerRegistrationClaimed;
			}
		}
		if (disconnectBroker)
		{
			CS_LOCK(lockBroker)
			{
				brokerDispatcher->DisconnectClient(clientId);
			}
		}
		if (hostDisconnected)
		{
			SPIN_LOCK(lockState)
			{
				dispatcherToInject = requesterDispatcher;
				pendingHostLoss = !dispatcherToInject;
			}
			if (dispatcherToInject)
			{
				dispatcherToInject->InjectException(RemoteViewModelHostDisconnectedError);
			}
		}
	}

	void RpcServerHelpers::Start(JsonChannelServer* _channelServer)
	{
		CHECK_ERROR(_channelServer, L"RpcServerHelpers::Start(...)#The channel server is null.");
		CHECK_ERROR(!channelServer, L"RpcServerHelpers::Start(...)#The helpers have already started.");
		channelServer = _channelServer;
		broadcastingClient->Connect(channelServer, broadcastingClient, taskQueue);
		SPIN_LOCK(lockState)
		{
			brokerDispatcher = broadcastingClient->GetDispatcher();
		}
		SPIN_LOCK(lockState)
		{
			admissionReady = true;
		}
	}

	vint RpcServerHelpers::Connect(const List<WString>& requiredServiceNames)
	{
		CHECK_ERROR(channelServer, L"RpcServerHelpers::Connect(...)#The helpers have not started.");
		CHECK_ERROR(!requesterDispatcher, L"RpcServerHelpers::Connect(...)#The requester has already connected.");
		auto requesterClientId = requesterClient->Connect(
			channelServer,
			requesterClient,
			taskQueue,
			brokerDispatcher->GetServerClientId(),
			requiredServiceNames
			);
		auto dispatcher = requesterClient->GetDispatcher();
		bool injectHostLoss = false;
		SPIN_LOCK(lockState)
		{
			requesterDispatcher = dispatcher;
			injectHostLoss = pendingHostLoss;
		}
		if (injectHostLoss)
		{
			dispatcher->InjectException(RemoteViewModelHostDisconnectedError);
		}
		CS_LOCK(lockBroker)
		{
			brokerDispatcher->RegisterClient(requesterClientId);
		}
		CHECK_ERROR(taskQueueThread->Start(), L"RpcServerHelpers::Connect(...)#Failed to start the task queue thread.");
		SPIN_LOCK(lockState)
		{
			taskQueueStarted = true;
		}
		return requesterClientId;
	}

	RpcDispatcherClient* RpcServerHelpers::GetDispatcher()
	{
		CHECK_ERROR(requesterDispatcher, L"RpcServerHelpers::GetDispatcher()#The requester has not connected.");
		return requesterDispatcher;
	}

	Ptr<IDescriptable> RpcServerHelpers::RequestService(const WString& typeName)
	{
		CHECK_ERROR(requesterDispatcher, L"RpcServerHelpers::RequestService(...)#The requester has not connected.");
		bool initializeRpc = false;
		SPIN_LOCK(lockState)
		{
			initializeRpc = !rpcInitialized;
		}
		if (initializeRpc)
		{
			requesterDispatcher->Initialize();
			SPIN_LOCK(lockState)
			{
				rpcInitialized = true;
			}
		}
		auto service = requesterDispatcher
			->GetRpcLifecycle()
			->RequestService(typeName);
		CHECK_ERROR(service, L"RpcServerHelpers::RequestService(...)#Failed to request the service.");
		if (!BeginRunning())
		{
			throw rpc_controller::RpcInjectedException(RemoteViewModelHostDisconnectedError);
		}
		return service;
	}

	bool RpcServerHelpers::BeginRunning()
	{
		bool result = false;
		SPIN_LOCK(lockState)
		{
			if (
				phase == RequesterPhase::Starting &&
				hostId != InvalidRemoteViewModelClientId
				)
			{
				phase = RequesterPhase::Running;
			}
			result = phase == RequesterPhase::Running;
		}
		return result;
	}

	bool RpcServerHelpers::CanAdmitRenderer()
	{
		bool result = false;
		SPIN_LOCK(lockState)
		{
			result = phase == RequesterPhase::Running;
		}
		return result;
	}

	void RpcServerHelpers::BeginStopping()
	{
		SPIN_LOCK(lockState)
		{
			if (phase == RequesterPhase::Stopping)
			{
				return;
			}
			phase = RequesterPhase::Stopping;
		}
	}

	void RpcServerHelpers::Stop(const Func<void()>& stopServer)
	{
		BeginStopping();
		bool finalizeRpc = false;
		bool stopTaskQueue = false;
		SPIN_LOCK(lockState)
		{
			finalizeRpc = rpcInitialized && !hostLossClaimed;
			stopTaskQueue = taskQueueStarted;
		}
		if (finalizeRpc)
		{
			FinalizeRpcOnTaskQueue();
		}
		if (stopServer)
		{
			stopServer();
		}
		if (stopTaskQueue)
		{
			taskQueue->QueueExitTask();
			taskQueueThread->Wait();
		}
	}
}
