/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: Host.sln

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_DEMOINCLUDES
#define VCZH_WORKFLOW_COMPILER_GENERATED_DEMOINCLUDES

#include "Demo.h"
#include "MainWindow.h"

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::ScrollTemplateScript)
			DECL_TYPE_INFO(::darkskin::BottomScrollButtonTemplate)
			DECL_TYPE_INFO(::darkskin::BottomScrollButtonTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::DocumentViewerTemplate)
			DECL_TYPE_INFO(::darkskin::DocumentViewerTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::HScrollHandleTemplate)
			DECL_TYPE_INFO(::darkskin::HScrollHandleTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::HScrollTemplate)
			DECL_TYPE_INFO(::darkskin::HScrollTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::LeftScrollButtonTemplate)
			DECL_TYPE_INFO(::darkskin::LeftScrollButtonTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::RightScrollButtonTemplate)
			DECL_TYPE_INFO(::darkskin::RightScrollButtonTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::TopScrollButtonTemplate)
			DECL_TYPE_INFO(::darkskin::TopScrollButtonTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::VScrollHandleTemplate)
			DECL_TYPE_INFO(::darkskin::VScrollHandleTemplateConstructor)
			DECL_TYPE_INFO(::darkskin::VScrollTemplate)
			DECL_TYPE_INFO(::darkskin::VScrollTemplateConstructor)
			DECL_TYPE_INFO(::demo::MainWindow)
			DECL_TYPE_INFO(::demo::MainWindowConstructor)
			DECL_TYPE_INFO(::demo::ModalWindow)
			DECL_TYPE_INFO(::demo::ModalWindowConstructor)
#endif

			extern bool LoadDemoTypes();
		}
	}
}

#endif
