/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: GacUI TuiFakeDialogServiceUI

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_TUIFAKEDIALOGSERVICEUIINCLUDES
#define VCZH_WORKFLOW_COMPILER_GENERATED_TUIFAKEDIALOGSERVICEUIINCLUDES

#include "TuiFakeDialogServiceUI.h"

#endif
