/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: Generated_FullControlTest

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_FULLCONTROLTESTINCLUDES
#define VCZH_WORKFLOW_COMPILER_GENERATED_FULLCONTROLTESTINCLUDES

#include "FullControlTest.h"
#include "DocumentEditorBase.h"
#include "MainWindow.h"
#include "FullControlTest1.h"

#endif
