/***********************************************************************
Vczh Library++ 3.0
Developer: Zihan Chen(vczh)
GacUI::HScrollTemplate

This file is generated by: Vczh GacUI Resource Code Generator
***********************************************************************/

#include <math.h>
#include "GacStudioUI.h"

namespace darkskin
{
	// #region CLASS_MEMBER_GUIEVENT_HANDLER (DO NOT PUT OTHER CONTENT IN THIS #region.)

	// #endregion CLASS_MEMBER_GUIEVENT_HANDLER

	HScrollTemplate::HScrollTemplate()
	{
		draggingHandle = false;
		InitializeComponents();
	}
}
