/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_MULTILINEWINDOW
#define VCZH_WORKFLOW_COMPILER_GENERATED_MULTILINEWINDOW

#include "UiaListPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace uialist
{
	class MultilineWindow : public ::vl::presentation::controls::GuiWindow, public ::uialist::MultilineWindowConstructor, public ::vl::reflection::Description<MultilineWindow>
	{
		friend class ::uialist::MultilineWindowConstructor;
		friend class ::vl_workflow_global::__vwsnc30_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc31_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc32_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc33_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc34_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc35_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc36_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc37_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc38_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf60_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf61_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf62_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf63_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf64_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf65_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf66_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf67_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf68_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf69_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf70_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf71_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf72_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf73_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf74_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf75_UiaList_uialist_MultilineWindowConstructor___vwsn_uialist_MultilineWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<MultilineWindow>;
#endif
	public:
		bool __vwsn_prop_Open;
		bool GetOpen();
		void SetOpen(bool __vwsn_value_);
		::vl::Event<void()> OpenChanged;
		::vl::Ptr<::uialist::IStringsStrings> __vwsn_prop_Strings;
		::vl::Ptr<::uialist::IStringsStrings> GetStrings();
		void SetStrings(::vl::Ptr<::uialist::IStringsStrings> __vwsn_value_);
		::vl::Event<void()> StringsChanged;
	private:
		::vl::Ptr<::uialist::vm::ITextDialogViewModel> __vwsn_parameter_ViewModel;
	public:
		::vl::Ptr<::uialist::vm::ITextDialogViewModel> GetViewModel();
		MultilineWindow(::vl::Ptr<::uialist::vm::ITextDialogViewModel> __vwsn_ctor_parameter_ViewModel);
		~MultilineWindow();
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
