/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

GacGen.exe Resource.xml

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_PROPERTYWINDOW
#define VCZH_WORKFLOW_COMPILER_GENERATED_PROPERTYWINDOW

#include "UiaListPartialClasses.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace uialist
{
	class PropertyWindow : public ::vl::presentation::controls::GuiWindow, public ::uialist::PropertyWindowConstructor, public ::vl::reflection::Description<PropertyWindow>
	{
		friend class ::uialist::PropertyWindowConstructor;
		friend class ::vl_workflow_global::__vwsnc46_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc47_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc48_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc49_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc50_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc51_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc52_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc53_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc54_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc55_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc56_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc57_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc58_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc59_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc60_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc61_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc62_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc63_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc64_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc65_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc66_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc67_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc68_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc69_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc70_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc71_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc72_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend class ::vl_workflow_global::__vwsnc73_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__vl_reflection_description_IValueSubscription;
		friend struct ::vl_workflow_global::__vwsnf100_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf101_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf102_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf103_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf104_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf105_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf106_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf107_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf108_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__;
		friend struct ::vl_workflow_global::__vwsnf109_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf110_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf111_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf112_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf113_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf114_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf115_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf116_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf117_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf118_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf119_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf120_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf121_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf122_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf123_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf124_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf125_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf126_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf127_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf128_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf129_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf130_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf131_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf132_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf133_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf134_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf135_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf136_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf137_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf138_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__;
		friend struct ::vl_workflow_global::__vwsnf139_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize___;
		friend struct ::vl_workflow_global::__vwsnf140_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf141_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf142_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize__;
		friend struct ::vl_workflow_global::__vwsnf143_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf144_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf91_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf92_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf93_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf94_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf95_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf96_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf97_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf98_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
		friend struct ::vl_workflow_global::__vwsnf99_UiaList_uialist_PropertyWindowConstructor___vwsn_uialist_PropertyWindow_Initialize_;
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<PropertyWindow>;
#endif
	public:
		::vl::Ptr<::uialist::vm::ITextDialogViewModel> __vwsn_prop_Dialog;
		::vl::Ptr<::uialist::vm::ITextDialogViewModel> GetDialog();
		void SetDialog(::vl::Ptr<::uialist::vm::ITextDialogViewModel> __vwsn_value_);
		::vl::Event<void()> DialogChanged;
		bool __vwsn_prop_Open;
		bool GetOpen();
		void SetOpen(bool __vwsn_value_);
		::vl::Event<void()> OpenChanged;
		::vl::vint __vwsn_prop_SelectedRow;
		::vl::vint GetSelectedRow();
		void SetSelectedRow(::vl::vint __vwsn_value_);
		::vl::Event<void()> SelectedRowChanged;
		bool changingCell;
		::vl::presentation::GridPos previousCell;
		::vl::Ptr<::uialist::vm::ITextDialogViewModel> shownDialog;
		::vl::Ptr<::uialist::IStringsStrings> __vwsn_prop_Strings;
		::vl::Ptr<::uialist::IStringsStrings> GetStrings();
		void SetStrings(::vl::Ptr<::uialist::IStringsStrings> __vwsn_value_);
		::vl::Event<void()> StringsChanged;
	private:
		::vl::Ptr<::uialist::vm::IPropertyDialogViewModel> __vwsn_parameter_ViewModel;
	public:
		::vl::Ptr<::uialist::vm::IPropertyDialogViewModel> GetViewModel();
		PropertyWindow(::vl::Ptr<::uialist::vm::IPropertyDialogViewModel> __vwsn_ctor_parameter_ViewModel);
		~PropertyWindow();
	};

}
#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
